### ISSUE TITLE
batch.repository.isolationlevelforcreate=ISOLATION_READ_COMMITTED not setup in jobRepository using Junit

### ISSUE THREAD

**Issue by naveendahiya** [codecentric/spring-boot-starter-batch-web#14]
THe following issue with oracle is handlled by setting isolationforcreate=ISOLATION_READ_COMMITTED. It works fine when I run Normal batch through webservice call.Somehow when I run batch through Junit, this property is not getting set. 
P.S. I have made sure application.properties is getting loaded when this Junit starts as I am reading other parameters from this files too.
StacckTrace : 
org.springframework.dao.CannotSerializeTransactionException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?)]; ORA-08177: can't serialize access for this transaction
; nested exception is java.sql.SQLException: ORA-08177: can't serialize access for this transaction

**Comment by dickerpulli** [comment]
@naveendahiya Due to cleaning up issues list: Is this issue a problem anymore?

**Comment by dickerpulli** [comment]
closed for clean up
