### ISSUE TITLE
TransactionAwareMetricWriter doesn't play along with AsyncItemProcessor

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-starter-batch-web#16]
When the TransactionAwareMetricWriter.increment() is called from an asynchronous execution (via AsyncItemProcessor) TransactionSynchronizationManager.isSynchronizationActive() returns false and the increment is passed directly to the delegate instead of being buffered in the MetricContainer. So the increments aren't transactional.

The TransactionSynchronizationManager uses an ThreadLocal to store the synchronizations therefore the threads started for the asynchronous execution aren't aware of the transaction.

**Comment by denschu** [comment]
Basically all actions inside AsyncItemProcessors are not transactional, so please use the nonTransaction-methods instead or move the counting actions to the (Async)ItemWriter.
