### ISSUE TITLE
TransactionAwareMetricWriter reorders increments and resets

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-starter-batch-web#17]
Givent the following scenario (single threaded):
```
<tx begin>
increment a
increment a
reset a
increment a
increment a
<tx end>
```
I would expect counter `a` to have the value 2.
But since `TransactionAwareMetricWriter.afterCompletion()` first executes all increments and afterwards the resets, the counter `a` has the value 0.

**Comment by denschu** [comment]
So, should we remove the reset-method or fix the TransactionAwareMetricWriter :-)?

**Comment by joshiste** [comment]
+1 for removal

Am Montag, 12. Januar 2015 schrieb Dennis Schulte :

**Comment by denschu** [comment]
Fixed ordering...
