### ISSUE TITLE
BatchMetricsImpl uses MappedDiagnosticContext to determine StepName

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-starter-batch-web#18]
The BatchMetricsImpl fetches the StepExecutionIdentifier from the MappedDiagnosticContext.
This seems a bit awkward since MDC is only for logging purposes.

Better use `StepSynchronizationManager.getContext()` to obtain step-identifier?

~~It also causes problems when using partiotioning since LoggingListener.beforeStep isn't called for the slave-step and the counternames are prefixed whit the master-step-id~~

**Comment by denschu** [comment]
Switched to StepSynchronizationManager for Metrics.
