### ISSUE TITLE
Metrics when using partitioning

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-starter-batch-web#19]
I expected themetric-counters to be in the slaves' stepExecutionContexts when using partitioning, but they are in the masters. Is that expected behaviour?

Did somebody explore if they behave correctly when doing restarts while using partitioning?

**Comment by denschu** [comment]
Yes, we actually save them in the masters. When using partitioning please register the LoggerListener also in the slave-steps to ensure the MDC is correctly filled with the jobLogFileName for Logback. 

See example here:
https://github.com/codecentric/spring-boot-starter-batch-web/blob/master/src/test/resources/META-INF/spring/batch/jobs/partitioned-flat-file-job.xml

We are now using the StepSynchronizationManager in the Metrics to obtain the job and step identifiers, so here you should not get any problems anymore.
