### ISSUE TITLE
Asynch job run

### ISSUE THREAD

**Issue by ghirardinicola** [codecentric/spring-boot-starter-batch-web#34]
Hi,
is it possible to start a job and make the rest api return just after the start instead of waiting for the execution to finish?
Nicola

**Comment by tobiasflohre** [comment]
That's exactly what it should do.

**Comment by joshiste** [comment]
May be you have a SyncTaskExecutor configured? Try a pooled one.
Am 03.03.2016 20:01 schrieb "Tobias Flohre" <notifications@github.com>:

**Comment by tobiasflohre** [comment]
A little more details:
If you don't configure a bean of type TaskExecutor yourself, the configuration at https://github.com/codecentric/spring-boot-starter-batch-web/blob/master/src/main/java/de/codecentric/batch/configuration/TaskExecutorConfiguration.java will create a pooled TaskExecutor, and the REST API will return immediately.

**Comment by ghirardinicola** [comment]
I checked with the beans endpoint provided by spring boot and it seems i do have the default TaskExecutor : 
{
        "bean": "taskExecutor",
        "scope": "singleton",
        "type": "org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor",
        "resource": "class path resource [de/codecentric/batch/configuration/TaskExecutorConfiguration.class]",
        "dependencies": []
      },


Here the log of the job execution (started making a post on localhost:8181/batch/operations/jobs/openTesiopenData )

2016-03-04 10:12:13.221  INFO 17604 --- [nio-8181-exec-2] o.s.b.c.l.support.SimpleJobLauncher      : Job: [FlowJob: [name=openTesiopenData]] launched with the following parameters: [{run.id=1}]
2016-03-04 10:12:13.271  INFO 17604 --- [nio-8181-exec-2] d.c.batch.listener.ProtocolListener      : --------------------------------------------------------------------------------
Job openTesiopenData started with Job-Execution-Id 0 
Job-Parameter: 
  run.id=1
--------------------------------------------------------------------------------
2016-03-04 10:12:13.438  INFO 17604 --- [nio-8181-exec-2] o.s.batch.core.job.SimpleStepHandler     : Executing step: [step1]

Thank you very much for helping me
Nicola

**Comment by ghirardinicola** [comment]
Updates: 
* My job was not using the default taskExecutor
* Even if i use it, or use defined one, the problem remains
Can i do some tests to better debug the issue?

**Comment by tobiasflohre** [comment]
The asynchronicity kicks in in the SimpleJobLauncher line 128 - there the taskExecutor is used to spawn the job, and if the taskExecutor is the right one, SimpleJobLauncher should return immediately, and thus the REST post.

**Comment by naveendahiya** [comment]
Did you try any of the samples provided? What happens if the sample works
and you copy paste your functionality to adapt it?

**Comment by ghirardinicola** [comment]
Comparing the samples with my app i finally i found the problem: i was using a batchConfigurer, in order to use a custom repository, and it seems to use the synchExecutor by default in that case.
It also seems my custom repo is picked up even without BatchConfigurer.
Maybe a little bit more doc about the batchConfigurer (when to use, what else it exclude..) is useful.

@Bean
    public BatchConfigurer batchConfigurer(DataSource dataSource){
    	return new DefaultBatchConfigurer(dataSource);
    }

Thanks for the help!
