### ISSUE TITLE
JOB_LOG_PATH is not being honoured by the logback-batch-base.xml

### ISSUE THREAD

**Issue by gepowell** [codecentric/spring-boot-starter-batch-web#36]
Hi have a logback-spring.xml in my application with contents 

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="logback-batch-base.xml" />
    <logger name="org.springframework" level="INFO"/>
    <jmxConfigurator/>
</configuration>`

In my application.yml file I am defining 

`batch:
    joblog:
        path: /var/log/batch`

When I debug and breakpoint in JobLoggingApplicationListener I can see it getting the value from the Spring environment and setting the system property. However when a job runs, logback ignores it and goes with the default of /tmp. It also appears to ignore the standard Spring Boot LOG_PATH setting as well.

This split logging functionality is great but at the moment, I can't hand it over to the operations team as they will want to specify where the log files are created.

**Comment by tobiasflohre** [comment]
What happens if you set the system property by hand before starting the application? Does it work then?

**Comment by tobiasflohre** [comment]
I just checked, you're right. I didn't build that feature, maybe @joshiste knows more? Anyway, it worked in my example to use the standard Spring Boot property:
logging.path=/tmp/myspecialfolder
And I just saw: the operations endpoint that delivers the logfile for an execution does not take the JOB_LOG_PATH into account anyway, probably you're better off with the Spring Boot log file folder mechanism.

**Comment by gepowell** [comment]
Hi, Thanks again for the prompt response. I could've sworn that I'd tried the logging.path setting as well, but clearly not. I now have my log files appearing where I want them to be. I agree with the motivation of defining a separate job logging directory or at  least having the option. Good to give the Ops guys the facility to place the logs where they want.
