### ISSUE TITLE
Springfox Swagger UI doesn't see operations controller

### ISSUE THREAD

**Issue by brunnels** [codecentric/spring-boot-starter-batch-web#39]
I'm trying to get Springfox going to show the different controller endpoints.  The endpoints show up properly in the swagger2 docs at /v2/api-docs.  The /swagger-ui.html web frontend only shows the monitoring controller.  I've turned on debugging output from springfox and don't see any errors or any indicating an issue.  Do you have any idea why this wouldn't be working?  

Basic setup and operation for springfox can be found here http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api

**Comment by tobiasflohre** [comment]
I'm sorry, haven't worked with springfox nor swagger, and don't have the time right now to learn it. If you find a solution, please post it here.

**Comment by brunnels** [comment]
I've narrowed it down to Springfox not liking something about the `launch` method in JobOperationsController.  If I comment that method out then it's okay.  I also noticed that however Springfox is breaking on that method it's stopping everything because any other controller frontends that would have been generated after JobOperationsControllers are missing.

**Comment by brunnels** [comment]
Seems to be MutliValueMap<String, String> parameter.  Issue is resolved if I remove that.  Found an unanswered stackoverflow with the same thing.  http://stackoverflow.com/questions/38527410/swagger-ui-not-working-when-spring-controller-uses-parameter-map

I'll keep looking.

**Comment by brunnels** [comment]
Springfox issue.  https://github.com/springfox/springfox/issues/1353
Swagger API issue https://github.com/swagger-api/swagger-ui/issues/2241

> Query parameters with Maps are simply not supported in the specification, and therefore not in the UI. You can only have primitives, arrays of primitives for query and path parameters. If you have a Map, it should be in a body parameter with a POST operation. This is not a restriction of swagger-ui, it's a restriction of the OpenAPI Specification.

I guess I 'll see if I can do it like he says.

**Comment by brunnels** [comment]
Changing to `@RequestBody MultiValueMap<String, String> payload` resolves the problem.
