### ISSUE TITLE
Need a method to set serializer for JobRepository and JobExplorer

### ISSUE THREAD

**Issue by brunnels** [codecentric/spring-boot-starter-batch-web#40]
There's a bug described [here](http://stackoverflow.com/questions/22306080/spring-batch-jdbcexecutioncontextdao-java-util-mapentry-deserializer-issue-xs) with databases like postgres and sql server that requires setting the serializer on the JobRepositoryFactoryBean and JobExplorerFactoryBean to Jackson2ExecutionContextStringSerializer.  I don't see a way to do this via TaskExecutorBatchConfigurer other than overriding much of it.

**Comment by dickerpulli** [comment]
@brunnels Due to cleaning up issues list: Is this custom serializer needed any more?

**Comment by gavenkoa** [comment]
I need this feature. Our jobs are not restartable and we pass large objects between steps. Some of them are job scope and behind GCLIB proxies (obviously they cannot be recreated by Jackson deserializer).

This piece does great job to disable "enterprisy" feature of Spring Batch:

    public class FakeSerializer implements ExecutionContextSerializer {
        @Override
        public Map<String, Object> deserialize(InputStream inputStream) throws IOException {
            return new HashMap<>();
        }
        @Override
        public void serialize(Map<String, Object> object, OutputStream outputStream) throws IOException {
            outputStream.write("fake".getBytes(StandardCharsets.US_ASCII));
        }
    }

As @brunnels has written it is impossible to inject FakeSerializer without coping entire implementation of `BasicBatchConfigurer` or similar.

All implementations of `BatchConfigurer` don't share any code except rudimentary `JpaBatchConfigurer` ((

**Comment by dickerpulli** [comment]
Implemented with 65ce01a0a99a0abefad2b7e44bf7c719d95cdfef 
Just add bean of type ExecutionContextSerializer in your Spring application context.
