### ISSUE TITLE
[Bug]FileAppender's stop() method may need to be tweaked.

### ISSUE THREAD

**Issue by hanishi** [codecentric/spring-boot-starter-batch-web#41]
When FileAppender is used in combination with SiftingAppender, FileAppender instantiated later time, that is after the SiftingAppender's timeout value which is set to 30 minutes by default, will not be able to write to the filename that is set to a job name.

See:
https://github.com/qos-ch/logback/pull/327/

**Comment by dickerpulli** [comment]
The FileAppender class is part of Spring Batch code base. Please report issues there.
