### ISSUE TITLE
It doesn't work on Java 8 at 1.3.2.RELEASE

### ISSUE THREAD

**Issue by queryholic** [codecentric/spring-boot-starter-batch-web#43]
# Question
My project is based on Java 8 and I followed the guide from "Getting started" page. But, I received below error message.
Is that impossible to run spring-boot-starter-batch-web 1.3.2.RELEASE on Java 8?

P.S
I found an article that was suspected as a cause. Is it relevant?
- http://stackoverflow.com/questions/40314140/springboot-metricrepository

so.. should I use java 7?

# Output error message
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field metricRepository in de.codecentric.batch.configuration.BaseConfiguration required a bean of type 'org.springframework.boot.actuate.metrics.repository.MetricRepository' that could not be found.
	- Bean method 'actuatorMetricRepository' not loaded because @ConditionalOnJava (older than 1.8) found 1.8


Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.boot.actuate.metrics.repository.MetricRepository' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:60183', transport: 'socket'

Process finished with exit code 1
```

**Comment by dbsejr21** [comment]
Solved.

I realize the newest version is 1.4.0.RELEASE, not 1.3.2.RELEASE.

According to release notes, maybe the error about this issue was solved at 1.3.4.RELEASE.

Thanks. :)

**Comment by Jeff-Walker** [comment]
Thanks for figuring this out. I spend a bit of time on this.

Maybe update the getting started guide? I didn't notice what version was needed until I got to the documentation.

**Comment by dickerpulli** [comment]
Release tab is your friend
