### ISSUE TITLE
Rerunning jobs with identical parameters via REST API results in reuse of existing run.id

### ISSUE THREAD

**Issue by spoolphiz** [codecentric/spring-boot-starter-batch-web#49]
I'm the same implementation of RunIdIncrementer mentioned [here](https://github.com/codecentric/spring-boot-starter-batch-web/issues/38#issuecomment-250670656).

When starting the batch application the first time and POSTing a request to /batch/jobs/my-job everything works fine. When resending the same exact request a second time I see that the `parameters`passed to the RunIdIncrementer are empty causing `run.id` to be set to 1. This results in the following error:
```
Step already complete or not restartable, so no action to execute
```

Am I doing something wrong?

**Comment by peter-fe** [comment]
We actually had a similar problem, when executing the same job again in another thread just with some ms delay. So the increment of the run.id happened almost parallel (the first job was not finished yet so the increment was based on the same value)

To overcome this kind of race condition we changed the RunIdIncrementer like this:
(Works for our use case)

`public class RunIdIncrementer implements JobParametersIncrementer {
    private static final String RUN_ID_KEY = "run.id";
    private String key = RUN_ID_KEY;

    public final void setKey(final String runIdKey) {
        this.key = runIdKey;
    }

    public final JobParameters getNext(final JobParameters parameters) {
        return new JobParametersBuilder().addLong(key, System.currentTimeMillis()).toJobParameters();
    }
}`

**Comment by dickerpulli** [comment]
https://github.com/codecentric/spring-boot-starter-batch-web/issues/38#issuecomment-250670656 and https://github.com/codecentric/spring-boot-starter-batch-web/issues/49#issuecomment-345202027 are both workaround for a bug in Spring Batch (not spring-boot-starter-batch-web)
