### ISSUE TITLE
Consider adding Spring Boot 2 support

### ISSUE THREAD

**Issue by snicoll** [codecentric/spring-boot-starter-batch-web#52]
Relates to https://github.com/spring-projects/spring-boot/issues/13510

We are reviewing our [community starters list](https://github.com/spring-projects/spring-boot/blob/7683d346e31bbe0313a03ce487ee59454665a143/spring-boot-project/spring-boot-starters/README.adoc) and a quick look here suggests that this starter doesn’t yet support Spring Boot 2.

Can you please let us know if/when you plan to support Spring Boot 2?

Thanks!

**Comment by dickerpulli** [comment]
Yes, we plan to upgrade in the next weeks. Should we leave this issue open, so I can notify you when it is done?

**Comment by snicoll** [comment]
@dickerpulli thanks for the quick feedback. IMO the issue should either be closed as a duplicate of another issue or closed when the support is effectively available.

**Comment by dickerpulli** [comment]
I will close it when Spring Boot 2 support is done

**Comment by dickerpulli** [comment]
2.0.0.RELEASE now supports Spring Boot 2.x

**Comment by snicoll** [comment]
Sweet, thanks!
