### ISSUE TITLE
Create new method to return executions by job name

### ISSUE THREAD

**Issue by Ppto** [codecentric/spring-boot-starter-batch-web#54]
@RequestMapping(value = "/jobs/executions/{jobName}", method = RequestMethod.GET)
	public Set<Long> findLastExecutions(@PathVariable String jobName) throws NoSuchJobExecutionException {
		List<JobInstance> jobInstances = jobExplorer.getJobInstances(jobName, 0, 10);
		
		Set<JobExecution> jobExecutions = new HashSet<JobExecution>();
		for(JobInstance jobInstance : jobInstances){
			jobExecutions.addAll(jobExplorer.getJobExecutions(jobInstance));
		}
		
		if (jobExecutions.isEmpty()) {
			throw new NoSuchJobExecutionException("There is not any JobExecution for the job '" + jobName + "'.");
		}
		
		return runningExecutionTracker.getAllRunningExecutionIds();
	}

**Comment by dickerpulli** [comment]
Please create a merge request
