### ISSUE TITLE
Methods for get instances and jobexcutions by jobname

### ISSUE THREAD

**Issue by Ppto** [codecentric/spring-boot-starter-batch-web#55]
Hello! 👋 Please add me as a collaborator to this repo.

**Comment by dickerpulli** [comment]
No, can't do that. If you want to provide some code (what you intended to do in https://github.com/codecentric/spring-boot-starter-batch-web/issues/54), please create a pull request. This is the way you can collaborate. Also look here: https://help.github.com/categories/collaborating-with-issues-and-pull-requests/
