### ISSUE TITLE
springboot 2.2.1

### ISSUE THREAD

**Issue by slash33** [codecentric/spring-boot-starter-batch-web#60]
hi,
i upgrade from springboot 2.1.13 to 2.2.1 and startup failed with :

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'XXXX': Unsatisfied dependency expressed through field 'yyyy'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'XXXX' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

i remove batch-web-spring-boot-starter dependency and try again, server start and works.

will you maintain this library?

thanks.

**Comment by dickerpulli** [comment]
I have release a new version with Spring Boot 2.2.6.RELEASE
I hope this fixes your problem.

**Comment by slash33** [comment]
I will try, thank you very much

**Comment by slash33** [comment]
Hi,
with 2.0.3, you upgrade java to version 11 and now cant compile with 8 : 
class file has wrong version 55.0, should be 52.0

**Comment by dickerpulli** [comment]
I have released a new version with Java 8 compiled classes.

**Comment by slash33** [comment]
i try with 2.0.4 but have same problem !!

**Comment by dickerpulli** [comment]
I do need more details of the problem.
The message from above has XXX and YYY placeholders. What are those?

**Comment by slash33** [comment]
XXX is job configuration bean and YYYY is a service with @Service 
`@Configuration
public class ArchivageJobConfiguration {
	
	@Autowired
	private ContratService contratService;

	private final StepBuilderFactory stepBuilderFactory;

	public ArchivageJobConfiguration(StepBuilderFactory stepBuilderFactory,
			ApplicationContext applicationContext) {
		this.stepBuilderFactory = stepBuilderFactory;
	}

	@Bean("jobArchivage")
	public Job archivageJob(JobBuilderFactory jobBuilderFactory,
			@Value("${job.archivage.name}") String jobName, @Qualifier("stepRecuperationContrat") Step step1) {
		return jobBuilderFactory.get(jobName).incrementer(new RunIdIncrementer()).flow(step1).end().build();
	}

	@Bean("stepRecuperationContrat")
	public Step step1(@Value("${job.archivage.step1.name}") String stepName,
			@Value("${job.archivage.chunk}") int chunk) {
		return stepBuilderFactory.get(stepName).<Contrat, Contrat>chunk(1).reader(contratsArchivablesReader())
				.processor(processor()).writer(writer()).build();
	}

	@Bean("readerArchivage")
	@StepScope
	public ListItemReader<Contrat> contratsArchivablesReader() {
		return new ListItemReader<Contrat>(contratService.getContratsArchivable());
	}

	@StepScope
	@Bean
	public ItemProcessor<Contrat, Contrat> processor() {
		return new ContratItemProcessor();
	}

	@StepScope
	@Bean
	public ItemWriter<Contrat> writer() {
		return new ContratItemWriter();
	}
}
`

**Comment by dickerpulli** [comment]
Looks like ContratService has not been created properly. Can I access the code in a public GitHub?

**Comment by slash33** [comment]
no i cant !!

**Comment by dickerpulli** [comment]
So, I can't help you further more :-(
