### ISSUE TITLE
documentation link not working

### ISSUE THREAD

**Issue by naveendahiya** [codecentric/spring-boot-starter-batch-web#62]
http://codecentric.github.io/spring-boot-starter-batch-web/

**Comment by naveendahiya** [comment]
It can be accessed here:
https://github.com/codecentric/spring-boot-starter-batch-web/blob/master/batch-web-spring-boot-docs/src/main/asciidoc/index.adoc

**Comment by dickerpulli** [comment]
There are sub folder for each version. For the latest documentation use

http://codecentric.github.io/spring-boot-starter-batch-web/current

**Comment by dickerpulli** [comment]
I created an index.html
