### ISSUE TITLE
Make the JobParametersConverter used in the JobExecutionController configurable

### ISSUE THREAD

**Issue by ingogriebsch** [codecentric/spring-boot-starter-batch-web#63]
Hello,

we have some special requirenments regarding the `JobParameters` in our project. It would help us immensively if it would be possible to configure the `JobParametersConverter` that is used in the ~`JobParametersController`~ `JobOperationsController`. This way we would be able to replace the currently used `DefaultJobParametersConverter` with a special `JobParametersConverter` implementation.

Is there any chance that you make this possible? :)

-- Edit: To be more precise in explaining our problem and about what we are asking.

We are currently using your library to be able to execute different jobs through REST. This is working quite nice. The only drawback that currently exists is, that the `JobOperationsController` declares, creates and uses a `JobParametersConverter` instance on its own.

https://github.com/codecentric/spring-boot-starter-batch-web/blob/534bf4fcbe02a96bad4b96a00dd1b3930eac479c/batch-web-spring-boot-autoconfigure/src/main/java/de/codecentric/batch/web/JobOperationsController.java#L157

The member is declared as `private`, it is not annotated as `@Autowired`, and the ctor does not allow to assign another instance. Therefore we are not able to explain the `JobOperationsController` to use another instance of `JobParametersConverter` as the one that is created while initialising the member (at least we don't see a possibility). An instance of `JobParametersConverter` that is part of the application-context would not help because it would not be injected into the instance of `JobOperationsController`.

We have some special cases we would like to do with the job-parameters that are send with the request. Therefore it would be really helpful if it would be possible to explain the `JobOperationsController` which instance of `JobParametersConverter` to use. :)

**Comment by dickerpulli** [comment]
The instantiation of `JobParametersConverter` is not part of our code base. As long as I can see the `JobParametersConverter` is instantiated as `DefaultJobParametersConverter` in `JobLauncherCommandLineRunner`. The default can be **overridden** by providing an own instance of (custom) `JobParametersConverter`. When you add a custom `JobParametersConverter` to Spring Context this one would be used there.

You mentioned a `JobParametersController`. Where does this Controller come from? It is neither part of our repo nor of Spring Batch itself.

**Comment by ingogriebsch** [comment]
> You mentioned a `JobParametersController`. Where does this Controller come from? It is neither part of our repo nor of Spring Batch itself.

Sorry for the mistake, I meant `JobOperationsController`. I corrected my original description.

> The instantiation of `JobParametersConverter` is not part of our code base. As long as I can see the `JobParametersConverter` is instantiated as `DefaultJobParametersConverter` in `JobLauncherCommandLineRunner`. The default can be **overridden** by providing an own instance of (custom) `JobParametersConverter`. When you add a custom `JobParametersConverter` to Spring Context this one would be used there.

I was probably not precise enough... Therefore, I enhanced the description of the issue! :)

**Comment by dickerpulli** [comment]
Ok.
Now I get your point. :-)

I made a change to support your request and released a new version. (2.1.0.RELEASE)

You just have to a custom bean of type JobParametersConverter in your Spring context and the autoconfigure mechanism would choose this one.

**Comment by dickerpulli** [comment]
@ingogriebsch would be nice to get feedback. Thanks.
