### ISSUE TITLE
cant inject service in step or tasklet

### ISSUE THREAD

**Issue by slash33** [codecentric/spring-boot-starter-batch-web#64]
Hi, 

With spring boot 2.4.1, cant inject service inside tasklet or step : 
Field loggerService in com.test.task.TaskTasklet required a bean of type 'com.test.service.LoggerService' that could not be found.

I make a reproductible example :
https://github.com/slash33/batch

if u use pom : pom_without_codecentric_starter.xml, only spring dependencies, batch works.

thanks.

[https://github.com/codecentric/spring-boot-starter-batch-web/issues/60](url)

**Comment by slash33** [comment]
Dont know why but i need to create a config class that extends AutomaticJobRegistrarConfigurationSupport with same code as you and it works !!!

@Configuration
public class AutomaticJobRegistrarConfiguration extends AutomaticJobRegistrarConfigurationSupport {
...... same code as u
}

Can you explain to me where the problem comes from?

Thanks

**Comment by slash33** [comment]
the annotation in AutomaticJobRegistrarConfiguration : 
@ConditionalOnMissingBean({AutomaticJobRegistrarConfigurationSupport.class}) seems to be the problem

**Comment by dickerpulli** [comment]
Hi.

You have to declare the Logger service inside the JobConfiguration.

JobConfiguration.java
```java
  @Bean
  public LoggerService loggerService() {
    return new LoggerServiceImpl();
  }
```

As documented in http://codecentric.github.io/spring-boot-starter-batch-web/current/#_getting_started (Section 3.3) each JobConfiguration get its own child ApplicationContext. This means the LoggerService, currently existing as bean in the parent context is not visible inside the Job scope. Therefor you need to create the instance inside the JobConfiguration.

**Comment by slash33** [comment]
Hi,
Will try this and close !!!
thank you so much
