### ISSUE TITLE
Upgrade to Spring Boot 2.4

### ISSUE THREAD

**Issue by pthorson** [codecentric/spring-boot-starter-batch-web#66]
After upgrading Spring Boot from 2.2.6 to 2.4.13, the JobMonitoringController /jobs returns an empty Set. 

It looks like some change related to Spring Batch 4.3.x as when I override the managed version of Spring Batch Core from 4.3.4 to 4.2.8.RELEASE, the job names are returned as expected.

This is for Java Configured jobs. I have not tried XML. 

I can see from the logs that the jobs are registered:
... c.b.c.AutomaticJobRegistrarConfiguration : Register jobs from class ...

And I can walkthrough the JobLoader registering each of the batches, but when /jobs is called the jobRegistry map is empty.

Versions:
Batch Web Spring Boot Starter 2.1.0.RELEASE
Spring Boot Version 2.4.13

**Comment by Springjunky** [comment]
Hi @pthorson we are still using spring-boot-starter-batch-web .. is there _any_ reaction or solution according to your issue ??
Is this repository still dead ?

**Comment by dickerpulli** [comment]
@pthorson Can you try with the latest version. I just released 2.2.0 with support for Spring Boot 2.6.7.

**Comment by Springjunky** [comment]
@dickerpulli I will try it as soon as possible, thank you very much for upgrading the framework

**Comment by Springjunky** [comment]
I have written a sample SpringBoot/-Batch with some Jobs .. one job is a long-time-processing Job.

For all tests I created my own MdcThreadPoolTaskExecutor named as Bean "taskExecutor" and wired it with
```
@Autowired
@Qualifier("taskExecutor")
  private TaskExecutor taskExceuter;
```
without explizit create and wire this SpringBoot reports an Error
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Field taskExceuter in .....jobs.SimpleLongRunningJavaExampleJob required a single bean, but 2 were found:
        - applicationTaskExecutor: defined by method 'applicationTaskExecutor' in class path resource [org/springframework/boot/autoconfigure/task/TaskExecutionAutoConfiguration.class]
        - taskScheduler: defined by method 'taskScheduler' in class path resource [org/springframework/boot/autoconfigure/integration/IntegrationAutoConfiguration$IntegrationTaskSchedulerConfiguration.class]
```
after that I started the SpringBoot and the long-time-processing-job with a shell-script (curl .../jobs/<jobname> and checked the endpoints of the
```
JobMonitoringController
JobOperationsController
```
with
```
batch.web.operations.base=/batch
batch.web.monitoring.base=/batch/monitoring
```

| Endpoint | Result | as Expected | Error in log | Remark |
|---|---|---|---|---|
|/batch/jobs/|job started| yes | no | parameters passed as expecetd with curl| 
|/batch/jobs/executions/{id}|status UNKNOWN(job running) or completed (job finished| yes | no | RequestMethod.DELETE not tested |
|/batch/jobs/executions/{id}/log|log shown| yes | no | -|
|/batch/monitoring/jobs| JSON list of XML and Java Jobs | yes | no| - |
|batch/monitoring/jobs/runningexecutions| empty if not job is running, id if job is running | yes | no | -|
|batch/monitoring/jobs/executions/{id}|JSON with job information after job was finished| yes | no | -|

I seemed to be everything works as expected !

**Comment by dickerpulli** [comment]
I just created a new release [2.3.0](https://github.com/codecentric/spring-boot-starter-batch-web/releases/tag/2.3.0) including Spring Boot 2.7.2

**Comment by Springjunky** [comment]
Thank you very much for this release.

I have repeated all manual test like described above, everything works as expected. :-)
In my opinion this issue can be closed
